import type { Prompt } from './content'
import type { Locale } from './language'

export const designCheckIds = ['design-0', 'design-1', 'design-2'] as const
const copy = {
  title: ['Azure HLD and LLD · optional', 'HLD et LLD Azure · facultatif'],
  intro: ['After reviewing the implementation, document the complete solution as an Azure high-level design (HLD) and low-level design (LLD). This optional visual task adds no fixed agenda time and never blocks resumption, discussion or main progress. Required architecture decisions and IaC remain part of the core scope.', 'Après la revue de l’implémentation, documentez la solution complète par un HLD et un LLD Azure. Cette tâche visuelle facultative n’ajoute aucun créneau fixe et ne bloque ni la reprise, ni la discussion, ni la progression principale. Les décisions d’architecture et l’IaC restent dans le périmètre obligatoire.'],
  prerequisites: ['Use the reviewed requirements, decisions and current code, IaC and pipeline artifacts. Python diagrams needs an authorized Python environment, the diagrams package and the system Graphviz dot executable; the Python graphviz package alone is insufficient. Verify Azure icon classes exist before use. Do not change machine settings or install tools without approval.', 'Utilisez les exigences, décisions et artefacts actuels de code, d’IaC et de pipelines. Python diagrams nécessite un environnement Python autorisé, le package diagrams et l’exécutable système Graphviz dot ; le package Python graphviz seul ne suffit pas. Vérifiez les classes d’icônes Azure avant utilisation. Ne modifiez pas le poste et n’installez rien sans autorisation.'],
  hld: ['HLD: responsibilities, actors, system boundaries and main data/identity flows across add-ins, generation, Azure and external platforms.', 'HLD : responsabilités, acteurs, frontières et flux principaux de données et d’identité entre compléments, génération, Azure et plateformes externes.'],
  lld: ['LLD: resource and interface details grounded in actual decisions, code and IaC. Map identities, network and configuration where decided; list unresolved values instead of inventing them.', 'LLD : détails des ressources et interfaces fondés sur les décisions, le code et l’IaC. Reliez identité, réseau et configuration lorsqu’ils sont décidés ; listez les valeurs inconnues sans les inventer.'],
  outputs: ['Keep editable Python generators, separate hld.png + hld.svg and lld.png + lld.svg, reproducible commands, a design narrative and component-to-artifact traceability. Reuse the python-diagrams paired-output helper when available.', 'Conservez les générateurs Python modifiables, hld.png + hld.svg et lld.png + lld.svg séparés, les commandes reproductibles, une explication et la traçabilité composants/artefacts. Réutilisez l’utilitaire de double sortie python-diagrams si disponible.'],
  boundary: ['Label proposed, implemented and unverified elements. Code or diagrams are not proof of deployed infrastructure. No customer-tenant access, resource creation, deployment or implementation changes are requested. If rendering is blocked, keep the sources and mark PNG/SVG not generated. Skipping this task never blocks later steps.', 'Distinguez proposé, implémenté et non vérifié. Le code ou les diagrammes ne prouvent pas une infrastructure déployée. Aucun accès au tenant client, création de ressource, déploiement ou changement d’implémentation n’est demandé. Si le rendu est bloqué, conservez les sources et indiquez PNG/SVG non générés. Ignorer cette tâche ne bloque jamais la suite.'],
  request: ['Using business-brief.txt, solution-scope.txt and architecture.png in knowledge-docs, the reviewed architecture decisions and current code, IaC and CI/CD artifacts, produce an Azure high-level design (HLD) and low-level design (LLD) for the complete reporting solution. Cover Word and PowerPoint add-ins, the ASP.NET Core .NET 10 generation backend using Aspose.Words and Aspose.Slides on Azure App Service, supporting identity/data/storage integrations, infrastructure configuration and delivery automation. Use the Python diagrams library with verified Azure icon classes and Graphviz to render separate HLD and LLD diagrams as both PNG and SVG. Keep editable Python sources, reproducible rendering instructions, a concise design narrative and a component-to-artifact traceability table. Reuse the existing python-diagrams resource and paired-output helper where available. Show responsibilities, boundaries and main flows in the HLD; ground LLD resources, interfaces, identity, network and configuration in actual code/IaC decisions. Label proposed, implemented and unverified elements and unresolved decisions instead of inventing settings. External platforms are dependencies, not systems to rebuild. Do not claim an as-built deployment, access a customer tenant, create resources, deploy or change implementation. Report unavailable prerequisites explicitly and show the outputs for review.', 'À partir de business-brief.txt, solution-scope.txt et architecture.png dans knowledge-docs, des décisions d’architecture revues et des artefacts actuels de code, d’IaC et de CI/CD, produisez un HLD et un LLD Azure pour la solution complète de reporting. Couvrez les compléments Word et PowerPoint, le backend ASP.NET Core .NET 10 utilisant Aspose.Words et Aspose.Slides sur Azure App Service, les intégrations d’identité, de données et de stockage, la configuration d’infrastructure et l’automatisation de livraison. Utilisez la bibliothèque Python diagrams avec des classes d’icônes Azure vérifiées et Graphviz pour générer deux diagrammes distincts HLD et LLD, chacun en PNG et SVG. Conservez les sources Python modifiables, les commandes reproductibles, une explication concise et une table de traçabilité composants/artefacts. Réutilisez la ressource python-diagrams et son utilitaire de double sortie si disponibles. Le HLD montre responsabilités, frontières et flux ; le LLD relie ressources, interfaces, identité, réseau et configuration aux décisions de code/IaC réelles. Distinguez proposé, implémenté, non vérifié et décisions ouvertes sans inventer de paramètres. Les plateformes externes sont des dépendances, pas des systèmes à reconstruire. Ne prétendez pas à une architecture déployée, n’accédez pas au tenant client, ne créez ni ne déployez de ressources et ne modifiez pas l’implémentation. Signalez les prérequis indisponibles et présentez les résultats pour revue.'],
  check0: ['I reviewed HLD and LLD against the actual scope and artifacts.', 'J’ai comparé HLD et LLD au périmètre et aux artefacts réels.'],
  check1: ['Both PNG/SVG pairs and editable sources are available, or the rendering blocker is recorded.', 'Les deux paires PNG/SVG et leurs sources sont disponibles, ou le blocage de rendu est consigné.'],
  check2: ['Proposed, implemented and unverified elements are distinguished; no deployment is claimed.', 'Les éléments proposés, implémentés et non vérifiés sont distingués ; aucun déploiement n’est prétendu.'],
  continue: ['Continue to Part 06 · resumption', 'Continuer vers la partie 06 · reprise'],
} as const satisfies Record<string, readonly [string, string]>
export const designText = (locale: Locale) => (key: keyof typeof copy): string => copy[key][locale === 'fr' ? 1 : 0]
export function designPrompt(locale: Locale): Prompt {
  const t = designText(locale)
  return { title: t('title'), text: t('request'), entry: 'squad-federation', requiresSetup: ['delivery-team'], squadTarget: 'implementation' }
}
