import type { Locale } from './language.ts'

// Every key has an authored English/French pair; no fallback or DOM substitution.
const messages = {
  language: ['Workshop language', 'Langue de l’atelier'],
  title: ['From data to reports, with HVE Squad', 'Des données aux rapports, avec HVE Squad'],
  titleFirst: ['From data to reports, ', 'Des données aux rapports, '],
  titleLast: ['with HVE Squad', 'avec HVE Squad'],
  subtitle: ['Hands-on workshop: scope and start an Office add-in', 'Atelier pratique : cadrer et commencer un complément Office'],
  prework: ['Before the workshop', 'Avant l’atelier'],
  preworkBadge: ['SELF-PACED · 0 LIVE MINUTES', 'À VOTRE RYTHME · 0 MINUTE EN DIRECT'],
  preworkIntro: ['Complete Parts 01 and 02 at your own pace before Thursday. They are not part of the live agenda. Part 03 starts with a readiness check-in, 09:00–09:10, then planning init and product work from 09:10 within the existing 09:00–10:00 slot. No full installation session in live time.', 'Terminez les parties 01 et 02 à votre rythme avant jeudi. Elles ne font pas partie du programme en direct. La partie 03 commence par une vérification de préparation de 09:00 à 09:10, puis l’initialisation et le travail produit dès 09:10 dans le créneau existant 09:00–10:00. Pas de session d’installation complète en direct.'],
  liveMinutes: ['live minutes', 'minutes en direct'],
  agenda: ['Live workshop agenda', 'Programme de l’atelier en direct'],
  agendaNote: ['Includes the 10-minute break. The final 30 minutes, 12:00–12:30, are protected for discussion.', 'Inclut la pause de 10 minutes. Les 30 dernières minutes, de 12:00 à 12:30, sont réservées à la discussion.'],
  materials: ['Your exercise materials', 'Vos supports d’exercice'],
  materialsIntro: ['Synthetic or blank files, not a completed solution or preinitialized team state. Keep completed worksheets in your participant repository, never in this guide.', 'Fichiers synthétiques ou vierges, pas une solution terminée ni un état d’équipe préinitialisé. Conservez les fiches complétées dans votre dépôt participant, jamais dans ce guide.'],
  download: ['Download', 'Télécharger'],
  lab: ['Report Studio lab', 'Laboratoire Report Studio'],
  synthetic: ['SYNTHETIC CASE · WORD + POWERPOINT', 'CAS SYNTHÉTIQUE · WORD + POWERPOINT'],
  labLead: ['A simple data contract. Editable output. Verifiable evidence.', 'Un contrat de données simple. Un résultat modifiable. Des preuves vérifiables.'],
  labDisclaimer: ['This lab only illustrates a local data preview in the guide: it is not an add-in and executes no Office, Fabric or Power BI integration.', 'Ce laboratoire illustre uniquement un aperçu local des données dans le guide : ce n’est pas un complément et il n’exécute aucune intégration Office, Fabric ou Power BI.'],
  firstSlice: ['Proposed first slice', 'Premier incrément proposé'],
  mve: ['Minimum viable experiment', 'Expérimentation minimale viable'],
  exploreContract: ['Explore the synthetic contract', 'Explorer le contrat synthétique'],
  simulation: ['LOCAL SIMULATION', 'SIMULATION LOCALE'],
  previewScenario: ['Preview scenario', 'Scénario à prévisualiser'],
  nominal: ['Two nominal periods', 'Deux périodes nominales'],
  negative: ['Negative cases', 'Cas négatifs'],
  tableCaption: ['Synthetic values — no Office document generated', 'Valeurs synthétiques — aucun document Office généré'],
  indicator: ['Indicator', 'Indicateur'],
  value: ['Value', 'Valeur'],
  unit: ['Unit', 'Unité'],
  unavailable: ['Unavailable', 'Indisponible'],
  blockInsertion: ['Block insertion under the exercise convention.', 'Bloquer l’insertion selon la convention de l’exercice.'],
  reference: ['Reference', 'Référence'],
  template: ['Template', 'Modèle'],
  expected: ['Expected: three values matching the selected dataset, then editable native content in the selected host. Insertion and its verification remain to be implemented in your project.', 'Attendu : trois valeurs correspondant au jeu choisi, puis un contenu natif modifiable dans l’application choisie. L’insertion et sa vérification restent à implémenter dans votre projet.'],
  variants: ['The null value and missing period are two test variants, not a third nominal period. The proposed convention blocks incomplete reports and preserves the existing document; obtain approval for it.', 'La valeur nulle et la période absente sont deux variantes de test, pas une troisième période nominale. La convention proposée bloque les rapports incomplets et préserve le document existant ; faites-la approuver.'],
  criteria: ['Proposed acceptance criteria', 'Critères d’acceptation proposés'],
  criteriaNote: ['Approve before implementation. The guide attests none of these tests in Office.', 'À approuver avant l’implémentation. Le guide n’atteste aucun de ces tests dans Office.'],
  technical: ['Technical decisions to make explicit', 'Décisions techniques à expliciter'],
  outsideScope: ['Outside workshop scope', 'Hors périmètre de l’atelier'],
  loadError: ['Unable to load progress. Saving is suspended: existing data has not been replaced. You can export this session’s progress or reset this workshop’s data.', 'Impossible de charger la progression. L’enregistrement est suspendu : les données existantes n’ont pas été remplacées. Vous pouvez exporter la progression de cette session ou réinitialiser les données de cet atelier.'],
  saveError: ['Progress was not saved. Keep this tab open and export your progress before leaving it.', 'La progression n’a pas été enregistrée. Gardez cet onglet ouvert et exportez votre progression avant de le quitter.'],
  copied: ['Copied. Review the request in your own project before sending it.', 'Copié. Relisez la demande dans votre propre projet avant de l’envoyer.'],
  clipboardError: ['Clipboard unavailable. Select the visible text and copy it manually; respect the required confirmations.', 'Presse-papiers indisponible. Sélectionnez le texte visible et copiez-le manuellement ; respectez les confirmations requises.'],
  resetDone: ['This workshop’s local data has been reset.', 'Les données locales de cet atelier ont été réinitialisées.'],
  resetError: ['Unable to reset: browser storage is inaccessible. Your data has not been replaced.', 'Réinitialisation impossible : le stockage du navigateur est inaccessible. Vos données n’ont pas été remplacées.'],
  copy: ['Copy', 'Copier'],
  shell: ['POWERSHELL · PREPARATION / INSTALLATION', 'POWERSHELL · PRÉPARATION / INSTALLATION'],
  lifecycle: ['LIFECYCLE · AGENT CONVERSATION', 'CYCLE DE VIE · CONVERSATION AVEC L’AGENT'],
  business: ['BUSINESS REQUEST · EXPECTED OUTCOME', 'DEMANDE MÉTIER · RÉSULTAT ATTENDU'],
  pasteOnly: ['Paste only the request below.', 'Collez uniquement la demande ci-dessous.'],
  confirmSteps: ['First confirm these steps in your project:', 'Confirmez d’abord ces étapes dans votre projet :'],
  locked: ['The Copy button is locked based on your self-report, not repository inspection. Do not bypass the step by copying manually.', 'Le bouton Copier est verrouillé selon vos déclarations, pas une inspection du dépôt. Ne contournez pas l’étape en copiant manuellement.'],
  selfPaced: ['Self-paced before Thursday · excluded from the 210-minute live agenda. Ready?', 'À votre rythme avant jeudi · hors des 210 minutes en direct. Prêt ?'],
  startLive: ['Start Part 03 at 09:00 with the readiness check-in; planning work from 09:10.', 'Commencez la partie 03 à 09:00 par la vérification de préparation ; planification dès 09:10.'],
  keyIdea: ['The key idea', 'L’idée clé'],
  inputs: ['Have these ready', 'À préparer'],
  beforeInstall: ['Repository and knowledge-docs before installation', 'Dépôt et knowledge-docs avant installation'],
  beforeEither: ['BEFORE EITHER INSTALLATION METHOD', 'AVANT TOUTE MÉTHODE D’INSTALLATION'],
  yourRepo: ['Your participant repository', 'Votre dépôt participant'],
  repoNote: ['No team state is supplied. The synthetic brief is available in Resources. Never copy a private scoping document into this site.', 'Aucun état d’équipe n’est fourni. Le cadrage synthétique est disponible dans les Ressources. Ne copiez jamais de cadrage privé dans ce site.'],
  setupBeforeWork: ['Setup before work', 'Constitution de l’équipe avant le travail'],
  setupCaption: ['SET UP · CONFIRM · REQUEST WORK', 'CONSTITUER · CONFIRMER · DEMANDER LE TRAVAIL'],
  lifecycleNote: ['Send each message separately in the agent conversation. init and promote are not PowerShell commands. In VS Code, use the complete slash command shown. These checkboxes record your confirmations: they create nothing and authorize no action.', 'Envoyez chaque message séparément dans la conversation de l’agent. init et promote ne sont pas des commandes PowerShell. Dans VS Code, utilisez la commande complète affichée. Ces cases enregistrent vos confirmations : elles ne créent rien et n’autorisent aucune action.'],
  outcomeCheck: ['Outcome to check before continuing', 'Résultat à vérifier avant de poursuivre'],
  setupSelfReport: ['Self-report after checking the real project. Completed setup does not mean business work has been executed.', 'Déclaration après vérification du projet réel. Une initialisation terminée ne signifie pas que le travail métier a été exécuté.'],
  separateRequest: ['Separate business request', 'Demande métier séparée'],
  outcomeCaption: ['WHAT YOU REQUEST · NOT INTERNAL MECHANISMS', 'CE QUE VOUS DEMANDEZ · PAS LES MÉCANISMES INTERNES'],
  requestPlanning: ['2. Request planning work', '2. Demander le travail de planification'],
  requestImplementation: ['3. Request implementation', '3. Demander l’implémentation'],
  observeCaption: ['WHAT YOU OBSERVE · DO NOT PASTE', 'CE QUE VOUS OBSERVEZ · NE PAS COLLER'],
  behaviors: ['Expected behaviors to verify', 'Comportements attendus à vérifier'],
  installTitle: ['3. Install after preparing the repository', '3. Installer après avoir préparé le dépôt'],
  installIntro: ['Continue only if the repository already contains the scoping document in knowledge-docs. If tools are installed, check their versions rather than reinstalling unnecessarily.', 'Continuez uniquement si le dépôt contient déjà le cadrage dans knowledge-docs. Si les outils sont installés, vérifiez leurs versions plutôt que les réinstaller inutilement.'],
  installMethod: ['Installation method', 'Méthode d’installation'],
  plugin: ['Plug-in · recommended', 'Plug-in · recommandé'],
  apm: ['APM · pinned', 'APM · épinglé'],
  pluginNote: ['Install both paired entries in your client. Marketplace installation does not guarantee v0.16.2: confirm actual versions and revisions.', 'Installez les deux entrées associées dans votre client. L’installation depuis la place de marché ne garantit pas v0.16.2 : confirmez les versions et révisions réelles.'],
  apmNote: ['After installing APM and authenticating to GitHub, run this command at the participant repository root. It pins the HVE Squad rehearsal reference; check resolved dependencies and their availability in your client.', 'Après installation d’APM et authentification GitHub, exécutez cette commande à la racine du dépôt participant. Elle épingle la référence de répétition HVE Squad ; vérifiez les dépendances résolues et leur disponibilité dans votre client.'],
  appInstall: ['In the App plug-in settings', 'Dans les paramètres de plug-ins de l’App'],
  appFind: ['Find the Peter-N91/hve-squad-plugin marketplace.', 'Recherchez la place de marché Peter-N91/hve-squad-plugin.'],
  appPair: ['Install hve-squad and hve-squad-hve-core together.', 'Installez hve-squad et hve-squad-hve-core ensemble.'],
  appCheck: ['Check versions and the presence of coordinators in the agent list.', 'Vérifiez les versions et la présence des coordinateurs dans la liste des agents.'],
  appLabels: ['Labels depend on the client and version. A CLI installation does not prove that the App uses the same resources.', 'Les libellés dépendent du client et de sa version. Une installation CLI ne prouve pas que l’App utilise les mêmes ressources.'],
  appGuide: ['App installation guide', 'Guide d’installation App'],
  pairing: ['Pairing, updates and client differences', 'Association, mises à jour et différences entre clients'],
  pairingNote: ['Do not overlay another standalone HVE Core version on the pair. Clients may have different plug-in directories. Check the client you actually use. For updates, follow the plug-in documentation: the second entry may need removal and reinstallation to pick up the correct revision. Do not change an installation used by other projects without approval.', 'Ne superposez pas une autre version autonome de HVE Core à la paire. Les clients peuvent avoir des dossiers de plug-ins différents. Vérifiez le client réellement utilisé. Pour les mises à jour, suivez la documentation : la seconde entrée peut nécessiter une suppression et réinstallation pour obtenir la bonne révision. Ne modifiez pas sans approbation une installation utilisée par d’autres projets.'],
  tools: ['Local tools and version references', 'Outils locaux et références de versions'],
  toolsNote: ['v0.16.2 is the Qubix rehearsal baseline, not prior validation of this Onepoint workshop. Record actual versions in “My workstation”. Git and an authenticated Copilot client are required. The Office toolchain needs a Node environment supported by the selected generator, an HTTPS development server and host authorization. This site itself uses Node 24+.', 'v0.16.2 est la référence de répétition Qubix, pas une validation préalable de cet atelier Onepoint. Consignez les versions réelles dans « Mon poste ». Git et un client Copilot authentifié sont requis. La chaîne Office nécessite un environnement Node pris en charge par le générateur choisi, un serveur de développement HTTPS et l’autorisation de l’application. Ce site utilise Node 24+.'],
  cliPrerequisites: ['CLI prerequisites', 'Prérequis CLI'],
  apmQuickstart: ['APM quickstart', 'Démarrage rapide APM'],
  toolsConsent: ['Installing a capability authorizes neither remote access nor deployment.', 'Installer une capacité n’autorise ni accès distant ni déploiement.'],
  actualClient: ['TEST THE ACTUAL CLIENT, NOT JUST THE TOOLS', 'TESTER LE CLIENT RÉEL, PAS SEULEMENT LES OUTILS'],
  pythonConditional: ['Python remains conditional', 'Python reste conditionnel'],
  optionalReader: ['Optional text PDF reader preparation', 'Préparation facultative d’un lecteur PDF textuel'],
  readerNote: ['Use an authorized environment and the same executable as the client. Reopen the client if its environment changed. The command checks an import, not extraction of the scoping document.', 'Utilisez un environnement autorisé et le même exécutable que le client. Rouvrez le client si son environnement a changé. La commande vérifie un import, pas l’extraction du document de cadrage.'],
  protectedDocument: ['Difficult or protected document', 'Document difficile ou protégé'],
  labLink: ['See the Report Studio lab: first slice, three indicators, negative cases, criteria and technical decisions.', 'Voir le laboratoire Report Studio : premier incrément, trois indicateurs, cas négatifs, critères et décisions techniques.'],
  exercises: ['Exercises and review points', 'Exercices et points de revue'],
  reviewCaption: ['REVIEW POINTS · NOT ONE REQUEST PER INTERNAL ROLE', 'POINTS DE REVUE · PAS UNE DEMANDE PAR RÔLE INTERNE'],
  prepareCaption: ['PREPARE, OBSERVE AND CONCLUDE', 'PRÉPARER, OBSERVER ET CONCLURE'],
  deliverables: ['DELIVERABLES', 'LIVRABLES'],
  evidence: ['Evidence to keep', 'Preuves à conserver'],
  checkpoint: ['YOUR CHECKPOINT', 'VOTRE POINT DE CONTRÔLE'],
  showIt: ['Can you show it?', 'Pouvez-vous le montrer ?'],
  selfReport: ['Local self-report, not automatic evidence of completion.', 'Déclaration locale, pas une preuve automatique d’achèvement.'],
  blocked: ['If you are blocked', 'En cas de blocage'],
  clientVersion: ['Copilot client and version', 'Client Copilot et version'],
  usedVersion: ['Version actually used', 'Version réellement utilisée'],
  squadVersion: ['Installed HVE Squad', 'HVE Squad installé'],
  checkedRevision: ['Checked version or revision', 'Version ou révision vérifiée'],
  coreVersion: ['Paired HVE Core', 'HVE Core associé'],
  checkedVersion: ['Checked version and revision', 'Version et révision vérifiées'],
  officeVersion: ['Office hosts, versions and OS', 'Applications Office, versions et système'],
  verifiedSupport: ['Verified support or blocker', 'Support vérifié ou blocage'],
  skip: ['Skip to content', 'Aller au contenu'],
  guide: ['WORKSHOP GUIDE', 'GUIDE DE L’ATELIER'],
  date: ['17 September 2026', '17 septembre 2026'],
  workstation: ['My workstation', 'Mon poste'],
  enableDark: ['Enable dark theme', 'Activer le thème sombre'],
  enableLight: ['Enable light theme', 'Activer le thème clair'],
  dark: ['Dark', 'Sombre'],
  light: ['Light', 'Clair'],
  journey: ['Journey', 'Parcours'],
  environment: ['Your environment, reported locally', 'Votre environnement, déclaré localement'],
  environmentPrivacy: ['No secrets, scoping documents or customer data. These values are not sent to a server.', 'Aucun secret, document de cadrage ou donnée client. Ces valeurs ne sont pas envoyées à un serveur.'],
  close: ['Close', 'Fermer'],
  environmentNote: ['These notes install and verify nothing. The export includes these fields; review it before sharing. No remote access is configured here.', 'Ces notes n’installent et ne vérifient rien. L’export inclut ces champs ; relisez-le avant partage. Aucun accès distant n’est configuré ici.'],
  navigation: ['Workshop navigation', 'Navigation de l’atelier'],
  learningJourney: ['YOUR LEARNING JOURNEY', 'VOTRE PARCOURS D’APPRENTISSAGE'],
  overview: ['Overview', 'Vue d’ensemble'],
  navPrework: ['Before the workshop · self-paced', 'Avant l’atelier · à votre rythme'],
  navLive: ['Live workshop · 09:00–12:30', 'Atelier en direct · 09:00–12:30'],
  preworkZero: ['Before the workshop · 0 live minutes', 'Avant l’atelier · 0 minute en direct'],
  resources: ['Resources and troubleshooting', 'Ressources et dépannage'],
  progress: ['My progress', 'Ma progression'],
  progressAria: ['Self-reported workshop progress', 'Progression déclarée dans l’atelier'],
  of: ['of', 'sur'],
  checkpoints: ['checkpoints · pre-work and live work · this browser', 'points de contrôle · préparation et direct · ce navigateur'],
  export: ['Export progress', 'Exporter la progression'],
  protectedTime: ['PROTECTED TIME', 'TEMPS PROTÉGÉ'],
  stopBuilding: ['Stop building. Make time for discussion.', 'Arrêtez de construire. Prenez le temps de discuter.'],
  logo: ['HVE Squad logo', 'Logo HVE Squad'],
  client: ['Copilot client', 'Client Copilot'],
  showNavigation: ['Show navigation', 'Afficher la navigation'],
  focus: ['Focus mode', 'Mode concentration'],
  print: ['Print the guide', 'Imprimer le guide'],
  prepareProject: ['PREPARE THE PROJECT FIRST', 'PRÉPARER D’ABORD LE PROJET'],
  installSequence: ['Repository → knowledge-docs → installation', 'Dépôt → knowledge-docs → installation'],
  installSequenceNote: ['Place the scoping document in your project before installing APM resources or both paired plug-ins.', 'Placez le cadrage dans votre projet avant d’installer les ressources APM ou les deux plug-ins associés.'],
  tabsNote: ['The tabs select your client. Agent selection comes after preparation and installation.', 'Les onglets sélectionnent votre client. La sélection de l’agent vient après la préparation et l’installation.'],
  selectAgent: ['SELECT THE AGENT, NOT A SKILL', 'SÉLECTIONNER L’AGENT, PAS UNE COMPÉTENCE'],
  lookFor: ['Look for', 'Rechercher'],
  labelsNote: ['Labels may vary by client and version. Then paste the request in that agent’s conversation, in your participant repository.', 'Les libellés peuvent varier selon le client et sa version. Collez ensuite la demande dans la conversation de cet agent, dans votre dépôt participant.'],
  reviewReset: ['Review reset options', 'Voir les choix de réinitialisation'],
  heroEyebrow: ['HANDS-ON WORKSHOP · THURSDAY 17 SEPTEMBER', 'ATELIER PRATIQUE · JEUDI 17 SEPTEMBRE'],
  heroIntro: ['Express the need, review decisions and retain evidence — from Word to PowerPoint, with Fabric and Power BI as the eventual target.', 'Exprimez le besoin, revoyez les décisions et conservez les preuves — de Word à PowerPoint, avec Fabric et Power BI comme cible à terme.'],
  beginPrework: ['Begin pre-work · Part', 'Commencer la préparation · Partie'],
  ready: ['Ready — start Part 03 at 09:00', 'Prêt — commencer la partie 03 à 09:00'],
  alreadyReady: ['Already ready? Start Part 03 at 09:00', 'Déjà prêt ? Commencer la partie 03 à 09:00'],
  reviewPrework: ['Review the pre-work', 'Revoir la préparation'],
  totalMinutes: ['210 live minutes, including break', '210 minutes en direct, pause incluse'],
  finalDiscussion: ['of protected final discussion', 'de discussion finale protégée'],
  beforeThursday: ['Before Thursday', 'Avant jeudi'],
  partsPrework: ['Parts 01–02 · self-paced', 'Parties 01–02 · à votre rythme'],
  methodTitle: ['Set up first. Request work next.', 'Constituer d’abord. Demander le travail ensuite.'],
  sequence: ['planning init → confirm → product work → promote → confirm → delivery init → confirm → implementation.', 'initialisation de la planification → confirmer → travail produit → promotion → confirmer → initialisation de la réalisation → confirmer → implémentation.'],
  methodNote: ['Business requests name the outcome, not roles or internal procedures. You remain responsible for decisions. Guide checkboxes record your self-reports; they execute and authorize nothing.', 'Les demandes métier nomment le résultat, pas les rôles ni les procédures internes. Vous restez responsable des décisions. Les cases du guide enregistrent vos déclarations ; elles n’exécutent et n’autorisent rien.'],
  continuous: ['One continuous live journey', 'Un parcours continu en direct'],
  learnMethod: ['LEARN THE METHOD', 'APPRENDRE LA MÉTHODE'],
  scope: ['Scope', 'Cadrer'],
  federate: ['Federate', 'Fédérer'],
  planningDelivery: ['Planning + delivery', 'Planification + réalisation'],
  test: ['Test', 'Tester'],
  officeSynthetic: ['Office · synthetic data', 'Office · données synthétiques'],
  resumeDiscuss: ['Resume + discuss', 'Reprendre + discuter'],
  evidenceNext: ['Evidence · next action', 'Preuves · prochaine action'],
  realOutcome: ['THE REAL EXPECTED OUTCOME', 'LE VÉRITABLE RÉSULTAT ATTENDU'],
  repeat: ['Be able to repeat it independently.', 'Pouvoir le refaire en autonomie.'],
  repeatNote: ['You do not need to finish the entire application: learn to scope, confirm, review, hand off and resume.', 'Il n’est pas nécessaire de finir toute l’application : apprenez à cadrer, confirmer, revoir, transmettre et reprendre.'],
  twoTargets: ['Two targets: Word and PowerPoint.', 'Deux cibles : Word et PowerPoint.'],
  sliceAgree: ['A first slice to agree.', 'Un premier incrément à convenir.'],
  syntheticLocal: ['Entirely synthetic local data.', 'Des données locales entièrement synthétiques.'],
  distinction: ['A distinction between generated, tested and not executed.', 'Une distinction entre généré, testé et non exécuté.'],
  experimentNote: ['A minimum experiment tests an uncertainty. An unexecuted experiment has no result.', 'Une expérimentation minimale teste une incertitude. Une expérimentation non exécutée n’a pas de résultat.'],
  generic: ['Report Studio: a generic scenario, not a private brief.', 'Report Studio : un scénario générique, pas un cadrage privé.'],
  privacyNote: ['The lab provides synthetic data and proposed criteria. An authorized scoping document stays in knowledge-docs at the participant repository root. The guide performs no uploads, integrations or publication.', 'Le laboratoire fournit des données synthétiques et des critères proposés. Un cadrage autorisé reste dans knowledge-docs à la racine du dépôt participant. Le guide ne réalise aucun téléversement, intégration ou publication.'],
  resourcesEyebrow: ['MAKE PROGRESS WITHOUT INVENTING', 'AVANCER SANS INVENTER'],
  resourcesLead: ['Context stays local. Evidence stays honest.', 'Le contexte reste local. Les preuves restent honnêtes.'],
  troubleshooting: ['When something blocks progress', 'Lorsqu’un blocage survient'],
  references: ['References to check in your environment', 'Références à vérifier dans votre environnement'],
  referencesNote: ['HVE Squad v0.16.2 is the Qubix rehearsal baseline. Confirm installed versions for Onepoint. App/CLI use the agent list or /agent with plain business requests. VS Code uses repository-scoped APM prompt files and the complete /squad or /squad-federation command shown. Verify the entries in GitHub Copilot Chat before the exercise; guide simulation is not actual squad dispatch.', 'HVE Squad v0.16.2 est la référence de répétition Qubix. Confirmez les versions installées pour Onepoint. L’App/CLI utilisent la liste des agents ou /agent avec des demandes métier simples. VS Code utilise les fichiers de commande APM du dépôt et la commande complète /squad ou /squad-federation affichée. Vérifiez les entrées dans GitHub Copilot Chat avant l’exercice ; la simulation du guide n’est pas une exécution réelle d’équipe.'],
  attribution: ['The sequence, synthetic case and requests are teaching adaptations in English and French. MVE concepts are paraphrased from HVE Core (CC BY 4.0). The unmodified HVE Squad logo is MIT licensed, copyright (c) 2026 Peter-N91. Logo and green/blue theme match the Qubix workshop, including its light and print variants. The original legal notices below are preserved verbatim.', 'La séquence, le cas synthétique et les demandes sont des adaptations pédagogiques en anglais et en français. Les concepts MVE sont reformulés depuis HVE Core (CC BY 4.0). Le logo HVE Squad non modifié est sous licence MIT, copyright (c) 2026 Peter-N91. Le logo et le thème vert/bleu correspondent à l’atelier Qubix, y compris les variantes claire et imprimée. Les mentions légales originales ci-dessous sont conservées à l’identique.'],
  license: ['Logo attribution and MIT license', 'Attribution du logo et licence MIT'],
  browserData: ['This browser’s data', 'Données de ce navigateur'],
  browserNote: ['Progress, language, VS Code mode and reported versions are kept locally, without synchronization, telemetry or delivery to the facilitator. This is not a workstation inspection tool. The export includes these settings and all seven parts, including the untimed pre-work; review it before sharing. Existing checkpoint IDs and export schema 1 are unchanged; old exports default to English and interactive mode. There is no import UI. Keep the JSON for manual restoration of the same storage key. An optional lang=en or lang=fr URL overrides language on opening; invalid URL languages safely use English without erasing progress. For a local HTML file, persistence may vary by browser: prefer export.', 'La progression, la langue, le mode VS Code et les versions déclarées restent locaux, sans synchronisation, télémétrie ni envoi à l’animateur. Ce n’est pas un outil d’inspection du poste. L’export inclut ces paramètres et les sept parties, dont la préparation non chronométrée ; relisez-le avant partage. Les identifiants des cases et le schéma d’export 1 restent inchangés ; les anciens exports utilisent l’anglais et le mode interactif par défaut. Il n’y a pas d’interface d’import. Conservez le JSON pour une restauration manuelle dans la même clé de stockage. Un paramètre d’URL facultatif lang=en ou lang=fr impose la langue à l’ouverture ; une valeur invalide utilise l’anglais sans effacer la progression. Pour un fichier HTML local, la persistance dépend du navigateur : privilégiez l’export.'],
  reported: ['checkpoints reported', 'points de contrôle déclarés'],
  resetLocal: ['Reset local data', 'Réinitialiser les données locales'],
  notFound: ['Step not found', 'Étape introuvable'],
  notFoundNote: ['This link does not match any step in the journey.', 'Ce lien ne correspond à aucune étape du parcours.'],
  returnOverview: ['Return to overview', 'Retour à la vue d’ensemble'],
  previousNext: ['Previous and next steps', 'Étapes précédente et suivante'],
  sourcesMaterials: ['Sources and materials', 'Sources et supports'],
  printNote: ['The four synthetic or blank materials for each language are available under Resources in the interactive guide. Parts 01–02 are self-paced before the workshop; Parts 03–07 and the break occupy 210 live minutes. The 09:00–09:10 readiness check-in is inside Part 03. This printout does not attest execution.', 'Les quatre supports synthétiques ou vierges de chaque langue sont disponibles dans les Ressources du guide interactif. Les parties 01–02 se font à votre rythme avant l’atelier ; les parties 03–07 et la pause occupent 210 minutes en direct. La vérification de préparation 09:00–09:10 fait partie de la partie 03. Cette impression n’atteste aucune exécution.'],
  workshop: ['HVE Squad hands-on workshop', 'Atelier pratique HVE Squad'],
  baseline: ['Rehearsal baseline v0.16.2, versions to confirm', 'Référence de répétition v0.16.2, versions à confirmer'],
  resetTitle: ['Reset this workshop’s data?', 'Réinitialiser les données de cet atelier ?'],
  resetNote: ['Only this workshop’s checked items and settings in this browser will be removed. No repository, team or document will change. Export first if needed.', 'Seuls les cases et paramètres de cet atelier dans ce navigateur seront supprimés. Aucun dépôt, équipe ou document ne changera. Exportez d’abord si nécessaire.'],
  keepData: ['Keep my data', 'Conserver mes données'],
  resetWorkshop: ['Reset this workshop', 'Réinitialiser cet atelier'],
  vscodeCaption: ['VS CODE · GITHUB COPILOT CHAT PROMPT FILES', 'VS CODE · FICHIERS DE COMMANDE GITHUB COPILOT CHAT'],
  vscodeInstall: ['Verified VS Code route: repository-scoped APM', 'Voie VS Code vérifiée : APM dans le dépôt'],
  vscodeInstallNote: ['Prepare the participant repository and knowledge-docs first. Install and authenticate APM, then run the command below at that root. APM supplies .github/prompts/squad/squad.prompt.md and squad-federation.prompt.md. Confirm /squad and /squad-federation in GitHub Copilot Chat before the exercise. A terminal installation or MCP-only setup does not supply proof of slash prompt availability.', 'Préparez d’abord le dépôt participant et knowledge-docs. Installez APM et authentifiez-vous, puis exécutez la commande ci-dessous à cette racine. APM fournit .github/prompts/squad/squad.prompt.md et squad-federation.prompt.md. Confirmez /squad et /squad-federation dans GitHub Copilot Chat avant l’exercice. Une installation terminal ou MCP seule ne prouve pas la disponibilité des commandes.'],
  duplicateWarning: ['Do not overlay plug-in and APM distributions in the same working environment. Inspect enabled resources first; use a clean participant repository and a dedicated approved VS Code profile without duplicate plug-in resources, or resolve duplicates with approval. Switching tabs installs nothing and preserves your App/CLI installation preference.', 'Ne superposez pas les distributions plug-in et APM dans le même environnement de travail. Inspectez d’abord les ressources actives ; utilisez un dépôt participant propre et un profil VS Code dédié approuvé sans ressources de plug-in en double, ou résolvez les doublons avec approbation. Changer d’onglet n’installe rien et préserve votre préférence d’installation App/CLI.'],
  vscodeUse: ['These are prompt-file commands in GitHub Copilot Chat, not terminal commands or slash skills. Main code blocks contain the complete request. Setup, promotion and read-only resumption never inherit the business-work mode.', 'Ce sont des commandes de fichiers de prompt dans GitHub Copilot Chat, pas des commandes terminal ni des compétences. Les blocs principaux contiennent la demande complète. Constitution d’équipe, promotion et reprise en lecture seule n’héritent jamais du mode de travail métier.'],
  businessMode: ['VS Code business-work mode', 'Mode de travail métier VS Code'],
  interactive: ['Interactive · default', 'Interactif · par défaut'],
  autonomous: ['Autonomous · opt in', 'Autonome · choix explicite'],
  autopilot: ['Autopilot · opt in', 'Pilote automatique'],
  modeSummary: ['Modes and required approvals', 'Modes et approbations nécessaires'],
  modeScope: ['Explicit opt-in, only for product and implementation. Does not unlock Copy or grant approval.', 'Choix explicite, uniquement pour le produit et l’implémentation. Ne débloque pas Copier et n’accorde aucune approbation.'],
  modeNote: ['Only the product and implementation requests use this selection. Interactive omits mode entirely. Autonomous uses a bounded, auto-validated review loop with required escalation. Autopilot runs the full research–plan–implement–review workflow; impactful-action approvals and final outcome validation still apply. Selecting a mode never unlocks a checkpoint or grants approval.', 'Seules les demandes produit et d’implémentation utilisent ce choix. Le mode interactif omet entièrement le paramètre mode. Le mode autonome utilise une boucle de revue bornée et auto-validée avec escalade obligatoire. Le pilote automatique réalise le cycle complet recherche–planification–implémentation–revue ; les approbations d’actions à impact et la validation finale du résultat restent nécessaires. Choisir un mode ne débloque aucune case et n’accorde aucune approbation.'],
  autopilotWarning: ['Caution: without squad=<registered-name>, federation autopilot coordinates the meta-selected sub-squads, not just one team. A real registered squad target narrows routing; never invent a name. The guide deliberately leaves this optional target out.', 'Attention : sans squad=<nom-enregistré>, le pilote automatique de fédération coordonne les sous-équipes choisies par le méta-coordinateur, pas une seule équipe. Une cible réellement enregistrée limite le routage ; n’inventez jamais de nom. Le guide omet volontairement cette cible facultative.'],
  parameters: ['Optional parameters · v0.16.2 reference', 'Paramètres facultatifs · référence v0.16.2'],
  parametersNote: ['Reference only, not text to paste into the main requests. Leave hints out unless they refer to real context. Single-squad init is expressed in request, without a standalone init flag. Federation init and promote are standalone flags, never mode values. Interactive means no mode argument.', 'Référence uniquement, pas du texte à coller dans les demandes principales. Omettez les indications qui ne correspondent pas au contexte réel. L’initialisation d’une équipe unique est exprimée dans request, sans drapeau init autonome. init et promote de fédération sont des drapeaux autonomes, jamais des valeurs de mode. Interactif signifie aucun argument mode.'],
  paramRequest: ['request: full business outcome or setup context, quoted with escaped quotes, backslashes and newlines.', 'request : résultat métier ou contexte de constitution complet, entre guillemets avec échappement des guillemets, barres obliques inverses et sauts de ligne.'],
  paramSquad: ['squad: optional existing registered sub-squad, federation only; omitted here.', 'squad : sous-équipe existante enregistrée, facultative et réservée à la fédération ; omise ici.'],
  paramProfile: ['profile: optional init profile hint; omit so the team proposes it from the need.', 'profile : indication facultative de profil à l’initialisation ; omettre pour que l’équipe le propose selon le besoin.'],
  paramPack: ['pack: optional technology pack(s), single squad only.', 'pack : ensemble(s) technologique(s) facultatif(s), équipe unique seulement.'],
  paramDiscovery: ['discovery: quick | standard | deep | skip, where applicable.', 'discovery : quick | standard | deep | skip, selon le contexte.'],
  paramTier: ['tier: fast | default, optional model-tier hint.', 'tier : fast | default, indication facultative de niveau de modèle.'],
  paramOwner: ['owner: optional existing named roster member; never invent one.', 'owner : membre nommé existant de l’équipe, facultatif ; ne jamais en inventer.'],
  urlLanguage: ['Unknown URL language: English is used; saved progress is preserved.', 'Langue d’URL inconnue : l’anglais est utilisé ; la progression enregistrée est préservée.'],
} satisfies Record<string, readonly [string, string]>
export type UIKey = keyof typeof messages
export function translator(locale: Locale) {
  return (key: UIKey): string => messages[key][locale === 'fr' ? 1 : 0]
}
